- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy NGINX config
  copy:
    src: ../../../../nginx/default.conf
    dest: /etc/nginx/sites-available/default
  notify: Restart nginx

- name: Start NGINX
  service:
    name: nginx
    state: started
    enabled: yes
